version: "3.3"

services:
  mongodb:
    hostname: mongodb
    image: mongo:3.6.9
    volumes:
      - ./mongo_data_dir:/data/db

  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:6.5.1
    environment:
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - thread_pool.search.queue_size=1000
      - thread_pool.search.size=30
      - thread_pool.search.min_queue_size=2000
      - thread_pool.search.max_queue_size=5000
      - thread_pool.search.auto_queue_frame_size=5000
      - thread_pool.search.target_response_time=1s
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - ./elastic_data_dir:/usr/share/elasticsearch/data

  dymer_entities:
    hostname: kms_entities
    image: demeterengteam/dymer_entities:20220210
    environment:
      - RRM_API=${RRM_API}
      - DYMER_UUID=${DYMER_UUID}
      - NODE_ENV=${NODE_ENV}
      - SOCS_DOMAIN=${SOCS_DOMAIN}
    depends_on:
      - elasticsearch

  dymer_forms:
    hostname: kms_forms
    image: demeterengteam/dymer_forms:20220210
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb

  dymer_services:
    hostname: kms_services
    image: demeterengteam/dymer_services:20220210
    environment:
      - NODE_ENV=${NODE_ENV}
      - RRM_API=${RRM_API}
      - ACS_SERVER=${ACS_SERVER}
    depends_on:
      - mongodb

  dymer_templates:
    hostname: kms_templates
    image: demeterengteam/dymer_templates:20220210
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb

  dymer_webserver:
    hostname: kms_webserver
    image: demeterengteam/dymer_webserver:20220210
    ports:
      - published: 8888
        target: 8080
    environment:
      - DYMER_CONTEXT_PATH=${DYMER_CONTEXT_PATH}
      - RRM_API=${RRM_API}
      - ACS_SERVER=${ACS_SERVER}
      - NODE_ENV=${NODE_ENV}
      - SOCS_DOMAIN=${SOCS_DOMAIN}

      #################################################

volumes:
  mongo_data_dir:
  elastic_data_dir:

