version: "3.3"

 

volumes:
    mongo_data:
    mongo_conf:
    elasticsearch_data:

 

services:
    mongodb:                        # ports: 27017
        hostname: mongodb
        image: mongo:3.6.9
        volumes:
          - mongo_data:/data/db
          - mongo_conf:/data/configdb
          - ./backups_mongo:/opt/backups

 

    elasticsearch:                  # ports: 9200 9300
        hostname: elasticsearch
        image: elasticsearch:6.5.1
        environment:
            - discovery.type=single-node
            - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
            - ./backups:/usr/share/elasticsearch/data/backups
            - ./dymer-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
 

    kms_webserver:                  # ports: 8080
        hostname: kms_webserver
        image: testgv/dymernodejs:14.18.1R
        ports:
          - published: 80
            target: 8080
        volumes:
            - ./dymer-webserver:/usr/src/app
        environment:
          - NODE_ENV=production
          - DYMER_UUID=${DYM_UUID}

 

    kms_services:                   # ports: 5050
        hostname: kms_services
        image: testgv/dymernodejs:14.18.1R
        extra_hosts:
          - "${DIH_PORTAL_NAME}:${DIH_PORTAL_ADDR}"
        volumes:
          - ./dymer-services:/usr/src/app
        environment:
          - NODE_ENV=production
          - DYMER_UUID=${DYM_UUID}
 

    kms_templates:                 # ports 4545
        hostname: kms_templates
        image: testgv/dymernodejs:14.18.1R
        depends_on:
          - mongodb
        volumes:
            - ./dymer-templates:/usr/src/app
        environment:
          - NODE_ENV=production
          - DYMER_UUID=${DYM_UUID}
 

    kms_forms:                     # ports: 4747
        hostname: kms_forms
        image: testgv/dymernodejs:14.18.1R
        depends_on:
          - mongodb
        volumes:
            - ./dymer-forms:/usr/src/app
        environment:
          - NODE_ENV=production
          - DYMER_UUID=${DYM_UUID}
 

    kms_entities:                  # ports: 1358
        hostname: kms_entities
        image: testgv/dymernodejs:14.18.1R
        depends_on:
          - elasticsearch
        volumes:
            - ./dymer-entities:/usr/src/app
        environment:
          - NODE_ENV=production
          - DYMER_UUID=${DYM_UUID}
    cache:
        image: redis:7.0.10-alpine3.17
        restart: always
        command: redis-server  --loglevel warning
        volumes: 
           - ./datacache:/data